const data = {
  developerRatings: [
    {
      daysSinceLastUpdate: 3,
      ratings: [
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Lagos',
            level: 'D3 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 2 - LOS',
          },
          attribute_score: [
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '1',
              note: '',
            },
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '1',
              note: '',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '1',
              note: '',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: 'N/A',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: 'N/A',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: 'N/A',
              note: '',
            },
          ],
          created_at: '2019-04-12T15:21:38.940Z',
          updated_at: '2019-04-12T15:21:38.940Z',
          average_score: '1.00',
        },
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Lagos',
            level: 'D3 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 2 - LOS',
          },
          attribute_score: [
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '1',
              note: '',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '1',
              note: '',
            },
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '1',
              note: '',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: 'N/A',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: 'N/A',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: 'N/A',
              note: '',
            },
          ],
          created_at: '2019-04-12T15:19:50.410Z',
          updated_at: '2019-04-12T15:19:50.410Z',
          average_score: '1.00',
        },
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Lagos',
            level: 'D3 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 2 - LOS',
          },
          attribute_score: [
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '1',
              note: '',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '1',
              note: '',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '1',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '1',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '1',
              note: '',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '2',
              note: '<p>Good</p>',
            },
          ],
          created_at: '2019-04-03T16:23:51.237Z',
          updated_at: '2019-04-03T16:23:51.237Z',
          average_score: '1.17',
        },
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Lagos',
            level: 'D3 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 2 - LOS',
          },
          attribute_score: [
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '1',
              note: '<p>adfasdfsdfsdaf</p>',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '2',
              note: '<p>adsfsfsdfsdfasdfsdf</p>',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '2',
              note: '<p>fadfasdfsdfsadf</p>',
            },
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '2',
              note: '<p>asdfasdfsdfsd</p>',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '1',
              note: '<p>sadfsdfsdfsdfsdfafdf</p>',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '2',
              note: '<p>adfasfsdfasfasdfa</p>',
            },
          ],
          created_at: '2018-09-28T12:51:03.922Z',
          updated_at: '2018-09-28T12:51:03.922Z',
          average_score: '1.67',
        },
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            email: 'allan.muhwezi@andela.com',
            first_name: 'Allan',
            last_name: 'Muhwezi',
            location: 'Lagos',
            level: 'D3 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 2 - LOS',
          },
          attribute_score: [
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '2',
              note: '<p>qerqwerwerwe</p>',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '2',
              note: '<p>qwrwerwrwerw</p>',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '2',
              note: '<p>wqerwqerwerwqr</p>',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '2',
              note: '<p>qwrwerwerwerwdfssd</p>',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '1',
              note: '<p>qwerwerwerwqerqqwer</p>',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '2',
              note: '<p>qwerwerqw</p>',
            },
          ],
          created_at: '2018-09-28T12:43:32.798Z',
          updated_at: '2018-09-28T12:43:32.798Z',
          average_score: '1.83',
        },
      ],
    },
    {
      developerId: '-KjcQJ3xLELVJCcJcfK3',
      daysSinceLastUpdate: 12,
      ratings: [
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Lagos',
            level: 'D2 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 9 - NBO',
          },
          attribute_score: [
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '-1',
              note: '<p>Test: needs work</p>',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '1',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '1',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '1',
              note: '',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '0',
              note: '<p>Test: needs work</p>',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '0',
              note: '<p>Test: needs work</p>',
            },
          ],
          created_at: '2019-04-03T16:23:51.237Z',
          updated_at: '2019-04-03T16:23:51.237Z',
          average_score: '0.33',
        },
      ],
    },
    {
      daysSinceLastUpdate: 12,
      ratings: [
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Lagos',
            level: 'D3 Developer',
            partner_name: 'Chikpea Test Rajo',
            partner_id: '-KlcUIvIyAFcNlii9n3J',
            cohort: 'Class 1 - KLA',
          },
          attribute_score: [
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '1',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '1',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '1',
              note: '',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '1',
              note: '',
            },
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '1',
              note: '',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '1',
              note: '',
            },
          ],
          created_at: '2019-04-03T16:23:51.237Z',
          updated_at: '2019-04-03T16:23:51.237Z',
          average_score: '1.00',
        },
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: '',
            level: 'D1 Developer',
            partner_name: '',
            partner_id: '-LBaO9Od8Tm_9jAoRj9F',
            cohort: '',
          },
          attribute_score: [
            {
              attribute_id: 7,
              attribute: 'Feelings About The Engagement',
              score: 'happy',
              note: '',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '2',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '2',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '2',
              note: '',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '2',
              note: '',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '2',
              note: '',
            },
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '2',
              note: '',
            },
            {
              attribute_id: 8,
              attribute: 'Feelings About Andela',
              score: 'happy',
              note: '',
            },
          ],
          created_at: '2018-05-25T17:17:01.024Z',
          updated_at: '2018-05-25T17:17:01.024Z',
          average_score: '2.00',
        },
      ],
    },
    {
      daysSinceLastUpdate: 12,
      ratings: [
        {
          note: '',
          rating_type: 'individual',
          developer_profile: {
            location: 'Nairobi',
            level: 'D2 Developer',
            partner_name: '',
            partner_id: '',
            cohort: 'Class 11 - NBO',
          },
          attribute_score: [
            {
              attribute_id: 2,
              attribute: 'Quantity',
              score: '1',
              note: '',
            },
            {
              attribute_id: 3,
              attribute: 'Initiative',
              score: '1',
              note: '',
            },
            {
              attribute_id: 4,
              attribute: 'Communication',
              score: '1',
              note: '',
            },
            {
              attribute_id: 5,
              attribute: 'Professionalism',
              score: '1',
              note: '',
            },
            {
              attribute_id: 6,
              attribute: 'Integration',
              score: '1',
              note: '',
            },
            {
              attribute_id: 1,
              attribute: 'Quality',
              score: '0',
              note: '<p>Test: needs work</p>',
            },
          ],
          created_at: '2019-04-03T16:23:51.237Z',
          updated_at: '2019-04-03T16:23:51.237Z',
          average_score: '0.83',
        },
      ],
    },
  ],
};

module.exports = data;
